services:
  db:
    image: postgres
    container_name: pizzaria_db
    environment:
      POSTGRES_DB: pizzaria
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
